#!/usr/bin/env python3
"""
Setup script for WhatsApp Trigger Manager
Creates .env file with user input
"""

import os

def setup_environment():
    """Setup environment variables"""
    print("🚀 WhatsApp Trigger Manager Setup")
    print("=" * 40)
    
    # Check if .env already exists
    if os.path.exists('.env'):
        overwrite = input("⚠️  .env file already exists. Overwrite? (y/N): ").lower()
        if overwrite != 'y':
            print("Setup cancelled.")
            return
    
    print("\n📝 Please provide the following information:")
    print("(Press Enter to use default values)")
    
    # Get base callback URL
    print("\n🌐 Base Callback URL:")
    print("   - For local development: http://localhost:5000")
    print("   - For ngrok: https://your-ngrok-url.ngrok-free.dev")
    print("   - For production: https://yourdomain.com")
    
    base_url = input("Base Callback URL [http://localhost:5000]: ").strip()
    if not base_url:
        base_url = "http://localhost:5000"
    
    # Get Flask environment
    flask_env = input("Flask Environment [development]: ").strip()
    if not flask_env:
        flask_env = "development"
    
    # Get Flask debug
    flask_debug = input("Flask Debug [True]: ").strip()
    if not flask_debug:
        flask_debug = "True"
    
    # Create .env file
    env_content = f"""# WhatsApp Trigger Manager Environment Variables
# Generated by setup.py

# Base callback URL (without trailing slash)
BASE_CALLBACK_URL={base_url}

# Flask settings
FLASK_ENV={flask_env}
FLASK_DEBUG={flask_debug}
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print(f"\n✅ .env file created successfully!")
    print(f"📁 Base Callback URL: {base_url}")
    print(f"🔧 Flask Environment: {flask_env}")
    print(f"🐛 Flask Debug: {flask_debug}")
    
    print("\n🚀 Next steps:")
    print("1. Install dependencies: pip install -r requirements.txt")
    print("2. Run the application: python backend.py")
    print("3. Open your browser: http://localhost:5000")
    print("4. Create your first trigger!")

if __name__ == '__main__':
    setup_environment()
